---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: "Include ansible-role-docker"
      ansible.builtin.include_role:
        name: "../../../ansible-role-docker/" # noqa: role-name
